security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
#        hwi:
#            id: hwi_oauth.user.provider
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            anonymous: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: ^/Login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }